// <auto-generated />
using System;
using GrillFusion_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrillFusion_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313034102_updateMenuItemModel")]
    partial class updateMenuItemModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrillFusion_API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GrillFusion_API.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burger",
                            Description = "Juicy smashed beef patty with cheddar cheese, lettuce, tomato, and our signature sauce on a brioche bun.",
                            Image = "",
                            Name = "Classic Smash Burger",
                            Price = 12.99,
                            SpecialTag = "Best Seller"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Burger",
                            Description = "Two flame-grilled patties with pepper jack cheese, jalapeños, crispy onions, and chipotle mayo.",
                            Image = "",
                            Name = "Double Inferno Burger",
                            Price = 15.99,
                            SpecialTag = "Spicy"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Burger",
                            Description = "Thick beef patty topped with smoky bacon, caramelized onions, BBQ sauce, and aged cheddar.",
                            Image = "",
                            Name = "BBQ Bacon Burger",
                            Price = 14.49,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 4,
                            Category = "Burger",
                            Description = "Grilled beef patty with sautéed mushrooms, Swiss cheese, garlic aioli, and arugula.",
                            Image = "",
                            Name = "Mushroom Swiss Burger",
                            Price = 13.99,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 5,
                            Category = "Grill",
                            Description = "12oz prime ribeye grilled to perfection, served with roasted garlic butter and seasonal vegetables.",
                            Image = "",
                            Name = "Ribeye Steak",
                            Price = 34.990000000000002,
                            SpecialTag = "Chef's Choice"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Grill",
                            Description = "Slow-cooked pork ribs glazed with our house BBQ sauce, served with coleslaw and cornbread.",
                            Image = "",
                            Name = "BBQ Ribs Half Rack",
                            Price = 24.989999999999998,
                            SpecialTag = "Best Seller"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Grill",
                            Description = "Marinated half chicken grilled over open flame, served with mashed potatoes and grilled corn.",
                            Image = "",
                            Name = "Grilled Chicken Platter",
                            Price = 18.989999999999998,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 8,
                            Category = "Grill",
                            Description = "Four rosemary-marinated lamb chops grilled to medium, served with mint jelly and roasted potatoes.",
                            Image = "",
                            Name = "Lamb Chops",
                            Price = 29.989999999999998,
                            SpecialTag = "New"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Sides",
                            Description = "Crispy golden fries topped with melted cheese, bacon bits, sour cream, and chives.",
                            Image = "",
                            Name = "Loaded Fries",
                            Price = 7.9900000000000002,
                            SpecialTag = "Best Seller"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Sides",
                            Description = "Hand-battered thick-cut onion rings fried to a golden crisp, served with smoky dipping sauce.",
                            Image = "",
                            Name = "Onion Rings",
                            Price = 5.9900000000000002,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 11,
                            Category = "Sides",
                            Description = "Creamy three-cheese macaroni baked with a golden breadcrumb crust.",
                            Image = "",
                            Name = "Mac & Cheese",
                            Price = 6.4900000000000002,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 12,
                            Category = "Sides",
                            Description = "Charred sweet corn on the cob brushed with herb butter and a sprinkle of smoked paprika.",
                            Image = "",
                            Name = "Grilled Corn",
                            Price = 4.4900000000000002,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 13,
                            Category = "Drinks",
                            Description = "Freshly squeezed lemonade blended with ripe mango purée, served over ice.",
                            Image = "",
                            Name = "Mango Lemonade",
                            Price = 4.9900000000000002,
                            SpecialTag = "New"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Drinks",
                            Description = "A thick vanilla milkshake with a hint of caramel and salted pretzel crumble on top.",
                            Image = "",
                            Name = "Smoky BBQ Shake",
                            Price = 6.9900000000000002,
                            SpecialTag = ""
                        },
                        new
                        {
                            Id = 15,
                            Category = "Drinks",
                            Description = "House-made lemonade with fresh mint, cucumber slices, and a splash of sparkling water.",
                            Image = "",
                            Name = "Iced Craft Lemonade",
                            Price = 3.9900000000000002,
                            SpecialTag = ""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GrillFusion_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GrillFusion_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrillFusion_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GrillFusion_API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
